"""init schema

Revision ID: 08c02fd08d2e
Revises: 
Create Date: 2026-01-14 03:28:08.693657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08c02fd08d2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barangs',
    sa.Column('id_barang', sa.Integer(), nullable=False),
    sa.Column('nama_barang', sa.String(), nullable=False),
    sa.Column('stok', sa.Integer(), nullable=False),
    sa.Column('harga_tetap', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_barang')
    )
    op.create_table('customers',
    sa.Column('id_customer', sa.Integer(), nullable=False),
    sa.Column('nama_customer', sa.String(), nullable=False),
    sa.Column('nama_perusahaan', sa.String(), nullable=False),
    sa.Column('alamat', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_customer')
    )
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_table('barang_harga_customers',
    sa.Column('id_barang_harga_customer', sa.Integer(), nullable=False),
    sa.Column('id_barang', sa.Integer(), nullable=False),
    sa.Column('id_customer', sa.Integer(), nullable=False),
    sa.Column('harga_khusus', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_barang'], ['barangs.id_barang'], ),
    sa.ForeignKeyConstraint(['id_customer'], ['customers.id_customer'], ),
    sa.PrimaryKeyConstraint('id_barang_harga_customer')
    )
    op.create_table('notas',
    sa.Column('id_nota', sa.Integer(), nullable=False),
    sa.Column('id_customer', sa.Integer(), nullable=True),
    sa.Column('nama_customer', sa.String(), nullable=True),
    sa.Column('tanggal', sa.DateTime(), nullable=False),
    sa.Column('nomor_nota', sa.Integer(), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_customer'], ['customers.id_customer'], ),
    sa.PrimaryKeyConstraint('id_nota')
    )
    op.create_table('detail_notas',
    sa.Column('id_detail_nota', sa.Integer(), nullable=False),
    sa.Column('id_nota', sa.Integer(), nullable=False),
    sa.Column('id_barang', sa.Integer(), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.Column('harga_satuan', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sub_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_barang'], ['barangs.id_barang'], ),
    sa.ForeignKeyConstraint(['id_nota'], ['notas.id_nota'], ),
    sa.PrimaryKeyConstraint('id_detail_nota')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detail_notas')
    op.drop_table('notas')
    op.drop_table('barang_harga_customers')
    op.drop_table('users')
    op.drop_table('customers')
    op.drop_table('barangs')
    # ### end Alembic commands ###
